[package]
name = "statements_to_books"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
fastnum = "0.1.9"
glob = "0.3.2"
polars = "0.45.1"
pyo3 = "0.23.3"
pyo3-polars = "0.19.0"
regex = "1.11.1"
