name: docker_check
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build . -f .devcontainer/Dockerfile -t built-image:scan
      - name: Run dockle
        uses: nickpowersys/dockle-action@main
        with:
          image: 'built-image:scan'
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'
